// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfwaXh3vwQTo1-K2-7A-s0KQ9JLLlhjwE',
    appId: '1:1087138322417:web:daf84ae6644ccb0ef0d650',
    messagingSenderId: '1087138322417',
    projectId: 'babylon-radio-app-dd53c',
    authDomain: 'babylon-radio-app-dd53c.firebaseapp.com',
    storageBucket: 'babylon-radio-app-dd53c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWANSSEHivl1UVqQ74j7sjdCfTvI5j5Vs',
    appId: '1:1087138322417:android:c356c482c4a39085f0d650',
    messagingSenderId: '1087138322417',
    projectId: 'babylon-radio-app-dd53c',
    storageBucket: 'babylon-radio-app-dd53c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIEfs_ueOzFu1CWoq0UcDpbu4vhMo7f0',
    appId: '1:1087138322417:ios:c063e2178d08b1a1f0d650',
    messagingSenderId: '1087138322417',
    projectId: 'babylon-radio-app-dd53c',
    storageBucket: 'babylon-radio-app-dd53c.firebasestorage.app',
    iosBundleId: 'com.example.babylonRadioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIEfs_ueOzFu1CWoq0UcDpbu4vhMo7f0',
    appId: '1:1087138322417:ios:c063e2178d08b1a1f0d650',
    messagingSenderId: '1087138322417',
    projectId: 'babylon-radio-app-dd53c',
    storageBucket: 'babylon-radio-app-dd53c.firebasestorage.app',
    iosBundleId: 'com.example.babylonRadioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfwaXh3vwQTo1-K2-7A-s0KQ9JLLlhjwE',
    appId: '1:1087138322417:web:f7c2739bd45754d5f0d650',
    messagingSenderId: '1087138322417',
    projectId: 'babylon-radio-app-dd53c',
    authDomain: 'babylon-radio-app-dd53c.firebaseapp.com',
    storageBucket: 'babylon-radio-app-dd53c.firebasestorage.app',
  );

}